version: '3.8'

networks:
  my_network:
    external: true

services:  
  zookeeper1.local:
    stdin_open: true 
    tty: true 
    build: .
    hostname: zookeeper1.local
    container_name: zookeeper1.local
    environment:
      MY_ID: 1
    networks:
      my_network:
        ipv4_address: 172.19.3.1
  zookeeper2.local:
    stdin_open: true 
    tty: true 
    build: .
    hostname: zookeeper2.local
    container_name: zookeeper2.local
    environment:
      MY_ID: 2
    networks:
      my_network:
        ipv4_address: 172.19.3.2
  zookeeper3.local:
    stdin_open: true 
    tty: true 
    build: .
    hostname: zookeeper3.local
    container_name: zookeeper3.local
    environment:
      MY_ID: 3
    networks:
      my_network:
        ipv4_address: 172.19.3.3
